name: Docker CD Only

on:
  workflow_dispatch: {}

jobs:
  docker-cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build JAR (skip tests)
        run: mvn -q -DskipTests clean package

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER }}/vegana-shop:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
